export const MEAL_LIST_REQUEST = 'MEAL_LIST_REQUEST';
export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS';
export const MEAL_LIST_FAIL = 'MEAL_LIST_FAIL';

export const MEAL_REQUEST = 'MEAL_REQUEST';
export const MEAL_SUCCESS = 'MEAL_SUCCESS';
export const MEAL_FAIL = 'MEAL_FAIL';

export const MEAL_RECOMMENDATIONS_REQUEST = 'MEAL_RECOMMENDATIONS_REQUEST';
export const MEAL_RECOMMENDATIONS_SUCCESS = 'MEAL_RECOMMENDATIONS_SUCCESS';
export const MEAL_RECOMMENDATIONS_FAIL = 'MEAL_RECOMMENDATIONS_FAIL';

export const MEAL_SORT_BY_CATEGORY_REQUEST = 'MEAL_SORT_BY_CATEGORY_REQUEST';
export const MEAL_SORT_BY_CATEGORY_SUCCESS = 'MEAL_SORT_BY_CATEGORY_SUCCESS';
export const MEAL_SORT_BY_CATEGORY_FAIL = 'MEAL_SORT_BY_CATEGORY_FAIL';

export const MEAL_ADD_REQUEST = 'MEAL_ADD_REQUEST';
export const MEAL_ADD_SUCCESS = 'MEAL_ADD_SUCCESS';
export const MEAL_ADD_FAIL = 'MEAL_ADD_FAIL';
