export const MEAL_LIST_REQUEST = 'MEAL_LIST_REQUEST';
export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS';
export const MEAL_LIST_FAIL = 'MEAL_LIST_FAIL';

export const MEAL_REQUEST = 'MEAL_REQUEST';
export const MEAL_SUCCESS = 'MEAL_SUCCESS';
export const MEAL_FAIL = 'MEAL_FAIL';

export const MEAL_SORT_BY_CATEGORY_REQUEST = 'MEAL_SORT_BY_CATEGORY_REQUEST';
export const MEAL_SORT_BY_CATEGORY_SUCCESS = 'MEAL_SORT_BY_CATEGORY_SUCCESS';
export const MEAL_SORT_BY_CATEGORY_FAIL = 'MEAL_SORT_BY_CATEGORY_FAIL';

export const MEAL_SORT_BY_PRICE_REQUEST = 'MEAL_SORT_BY_PRICE_REQUEST';
export const MEAL_SORT_BY_PRICE_SUCCESS = 'MEAL_SORT_BY_PRICE_SUCCESS';
export const MEAL_SORT_BY_PRICE_FAIL = 'MEAL_SORT_BY_PRICE_FAIL';

export const MEAL_SORT_BY_VEGETARIAN_REQUEST =
  'MEAL_SORT_BY_VEGETARIAN_REQUEST';
export const MEAL_SORT_BY_VEGETARIAN_SUCCESS =
  'MEAL_SORT_BY_VEGETARIAN_SUCCESS';
export const MEAL_SORT_BY_VEGETARIAN_FAIL = 'MEAL_SORT_BY_VEGETARIAN_FAIL';

export const MEAL_SORT_BY_POPULARITY_REQUEST =
  'MEAL_SORT_BY_POPULARITY_REQUEST';
export const MEAL_SORT_BY_POPULARITY_SUCCESS =
  'MEAL_SORT_BY_POPULARITY_SUCCESS';
export const MEAL_SORT_BY_POPULARITY_FAIL = 'MEAL_SORT_BY_POPULARITY_FAIL';
